import cPickle as pickle
import logging
import random
import time

from django.core.management.base import BaseCommand
from django.test.client import RequestFactory

from twttr import views
from twttr.models import User, Tweet


class Command(BaseCommand):
    """Seed the database with jeffbalogh's friends."""

    def handle(self, *args, **kw):
        num = int(args[0]) if args else 30
        rf = RequestFactory()
        users = pickle.load(open('users.txt')).values()
        while 1:
            start = time.time()
            for name in random.sample(users, num):
                request = rf.post('/post/%s' % name,
                                  {'tweet': 'I am a tweet generated by a robot'})
                request._dont_enforce_csrf_checks = True
                views.post(request, name)
            logging.info('Generated %s tweets in %.2f.' % (num, time.time() - start))
            time.sleep(1)
